<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Project -->
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<!-- <RootNamespace>Template</RootNamespace> -->
		<Configurations>Debug;Release;RelSelfContained;DebugAOT;ReleaseAOT</Configurations>

		<!-- Lang features -->
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- <AllowUnsafeBlocks>true</AllowUnsafeBlocks> -->

		<!-- Publish -->
		<PublishSingleFile>true</PublishSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<!-- <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract> -->
		<!-- <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract> -->
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<!-- Globalization -->
		<InvariantGlobalization>true</InvariantGlobalization>

		<!-- QOL -->
		<Deterministic>true</Deterministic>
		<PathMap>$(MSBuildProjectDirectory)=.</PathMap>
		<EnableSourceLink>false</EnableSourceLink>
		<DebugType>Portable</DebugType>

		<!-- Analyzers -->
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- Misc -->
		<ErrorReport>none</ErrorReport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='RelSelfContained|AnyCPU'">
		<Optimize>true</Optimize>
		<SelfContained>true</SelfContained>
		<DebugType>None</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugAOT|AnyCPU'">
		<Optimize>false</Optimize>
		<PublishAot>true</PublishAot>
		<StripSymbols>false</StripSymbols>
		<!-- <InvariantGlobalization>true</InvariantGlobalization> -->

		<IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
		<IlcOptimizationPreference>Balanced</IlcOptimizationPreference>
		<IlcDisableReflection>false</IlcDisableReflection>

		<DebuggerSupport>true</DebuggerSupport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseAOT|AnyCPU'">
		<Optimize>true</Optimize>
		<PublishAot>true</PublishAot>
		<StripSymbols>true</StripSymbols>
		<!-- <InvariantGlobalization>true</InvariantGlobalization> -->

		<IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
		<IlcOptimizationPreference>Speed</IlcOptimizationPreference>
		<IlcDisableReflection>false</IlcDisableReflection>

		<EventSourceSupport>false</EventSourceSupport>
		<StackTraceSupport>false</StackTraceSupport>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Snowyyd.AnalyzerConfig" Version="2.0.1">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

</Project>
